version: '3'

services:
  php:
    container_name: php
    build: ./docker
    volumes:
    - .:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 10080:80
    volumes:
    - .:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    - mailhog

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_yDB: local-db
      MYSQL_INITDB_ARGS: "--encoding=UTF-8"
      TZ: 'UTC'
    volumes:
    - .:/var/www
    ports:
    - 13306:3306

  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
